"""
notifications-service — REST API service
Auto-generated by IDP scaffold on 2026-05-15
"""

import os
import logging
from http.server import BaseHTTPRequestHandler, HTTPServer
import json

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
)
logger = logging.getLogger("notifications_service")

PORT = int(os.getenv("PORT", "8000"))


class Handler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):  # noqa: A002
        logger.info("%s - %s", self.address_string(), format % args)

    def _send_json(self, status: int, body: dict):
        payload = json.dumps(body).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def do_GET(self):  # noqa: N802
        if self.path == "/health":
            self._send_json(200, {"status": "ok", "service": "notifications-service"})
        elif self.path == "/":
            self._send_json(200, {"service": "notifications-service", "version": "0.1.0"})
        else:
            self._send_json(404, {"error": "not found"})

    # TODO: implement your domain logic here


if __name__ == "__main__":
    logger.info("Starting notifications-service on port %d", PORT)
    server = HTTPServer(("0.0.0.0", PORT), Handler)
    server.serve_forever()
