/**
 * Terraform module — payments-service (api)
 * Auto-generated by IDP scaffold on 2026-05-15
 *
 * Resources provisioned:
 *   - S3 bucket     : artifact and file storage
 *   - SSM parameter : runtime configuration
 *
 * Targets LocalStack for local development.
 * For production: remove the endpoint overrides and configure real AWS credentials.
 */

terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region                      = var.aws_region
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true   # required for LocalStack — avoids subdomain DNS resolution

  endpoints {
    s3  = var.localstack_endpoint
    ssm = var.localstack_endpoint
  }
}

# ── S3 Bucket ─────────────────────────────────────────────────────────────────
resource "aws_s3_bucket" "artifacts" {
  bucket = "${var.service_name}-artifacts"
  tags   = local.common_tags
}

# ── SSM Parameter (runtime config) ───────────────────────────────────────────
resource "aws_ssm_parameter" "config" {
  name  = "/${var.environment}/${var.service_name}/config"
  type  = "String"
  value = jsonencode({
    bucket_name = aws_s3_bucket.artifacts.bucket
    port        = 8000
  })
  tags = local.common_tags
}

locals {
  common_tags = {
    Service     = var.service_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}
